"""cs new — scaffold a new CloudSpells stack from a spell template.

Creates a `<name>/` directory containing `Pulumi.yaml` and `__main__.py`
generated by the named spell template.  Stack state is initialised lazily
on the first `cs up` call, so no Pulumi CLI or passphrase is required here.
"""

__all__ = ["new"]

from pathlib import Path
from typing import Annotated

import typer
from cloudspells.cli.console import console
from cloudspells.cli.templates import SPELL_REGISTRY, list_spells
from cloudspells.cli.templates import render as _render


def new(
    spell: Annotated[str | None, typer.Argument(help="Spell type to scaffold.")] = None,
    name: Annotated[str | None, typer.Argument(help="Stack directory name.")] = None,
    stack: Annotated[str, typer.Option(help="Pulumi stack name to initialise.")] = "dev",
    force: Annotated[bool, typer.Option("--force", help="Overwrite existing directory.")] = False,
    list_flag: Annotated[bool, typer.Option("--list", help="List available spell templates and exit.")] = False,
) -> None:
    """Scaffold a new CloudSpells stack from a spell template.

    Creates a `<NAME>/` directory containing `Pulumi.yaml` and
    `__main__.py` ready to configure and deploy.

    Raises:
        typer.Exit: On `--list`, on missing/unknown arguments, or when the
            target directory already exists without `--force`.

    Examples:
        cs new vcn my-network

        cs new oke my-cluster --stack prod

        cs new --list
    """
    if list_flag:
        console.print("[bold]Available spell templates:[/bold]")
        for s in list_spells():
            console.print(f"  {s}")
        raise typer.Exit()

    if spell is None or name is None:
        console.print("[red]Error:[/red] SPELL and NAME arguments are required.")
        console.print("  Usage: cs new <spell> <name>")
        console.print("  Use --list to see available spells.")
        raise typer.Exit(1)

    if spell not in SPELL_REGISTRY:
        console.print(f"[red]Error:[/red] Unknown spell '{spell}'.")
        console.print(f"  Available: {', '.join(list_spells())}")
        raise typer.Exit(1)

    out_dir = Path(name)
    if out_dir.exists() and not force:
        console.print(f"[red]Error:[/red] Directory '{name}' already exists.")
        console.print("  Use --force to overwrite.")
        raise typer.Exit(1)

    files = _render(spell, name, stack)
    out_dir.mkdir(parents=True, exist_ok=True)

    for filename, content in files.items():
        (out_dir / filename).write_text(content)

    console.print(f"[green]✓[/green] Created {name}/Pulumi.yaml")
    console.print(f"[green]✓[/green] Created {name}/__main__.py")
    console.print()
    console.print("[bold]Next steps:[/bold]")
    console.print(f"  cd {name}")
    console.print("  cs config set compartment_ocid <OCID>")
    console.print("  cs up --preview")
    console.print("  cs up")
